# Generated by Django 6.0.1 on 2026-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('trainer', 'Trainer'), ('user', 'User')], max_length=20),
        ),
    ]
