# Generated by Django 6.0.1 on 2026-01-27 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_role'),
        ('gymm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_text', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_workouts', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_workouts', to='accounts.account')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_text', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_diets', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='accounts.account')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
