# Generated by Django 6.0.1 on 2026-01-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_role'),
        ('gymm', '0003_alter_dietplan_unique_together_dailyrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyworkout',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyworkout',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='dailyworkout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.AlterField(
            model_name='trainerassignment',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='trainerassignment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainer', to='accounts.account'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='DailyWorkout',
        ),
        migrations.DeleteModel(
            name='DietPlan',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
